// packages/admin-ui/src/lib/components/products/ProductSeoTab.svelte
<script lang="ts">
  import { Label, Input, Textarea, Card, CardHeader, CardTitle, CardDescription, CardContent } from '$lib/components/ui';
  import { productsStore, type Product } from '$lib/stores/products';
  import { currentUser } from '$lib/stores/auth';
  import { saveStatusStore } from '$lib/stores/save-status';
  import { toast } from '$lib/stores/toast';
  import { createAutoSave } from '$lib/utils/auto-save';

  interface Props {
    product: Product;
  }

  let { product }: Props = $props();

  let metaTitle = $state('');
  let metaDescription = $state('');

  // Sync when product changes
  $effect(() => {
    metaTitle = product.metaTitle;
    metaDescription = product.metaDescription;
  });

  async function saveMetadata(field: 'title' | 'description', value: string) {
    if (!$currentUser?.id) {
      toast.error('You must be logged in to update products');
      return;
    }

    // Check if value actually changed
    const currentValue = field === 'title' ? product.metaTitle : product.metaDescription;
    if (value === currentValue) return;

    saveStatusStore.startSaving();
    try {
      await productsStore.updateProductMetadata({
        id: product.aggregateId,
        userId: $currentUser.id,
        metaTitle: field === 'title' ? value : metaTitle,
        metaDescription: field === 'description' ? value : metaDescription,
        expectedVersion: product.version,
        fulfillmentType: product.productType
      });
      saveStatusStore.completeSave();
      await productsStore.fetchProducts();
    } catch (error) {
      // Revert to previous value
      if (field === 'title') metaTitle = product.metaTitle;
      if (field === 'description') metaDescription = product.metaDescription;

      saveStatusStore.failSave();
      toast.error(error instanceof Error ? error.message : 'Failed to update metadata');
    }
  }

  const titleAutoSave = createAutoSave((value: string) => saveMetadata('title', value));
  const descriptionAutoSave = createAutoSave((value: string) => saveMetadata('description', value));

  function handleTitleChange(e: Event) {
    const target = e.target as HTMLInputElement;
    metaTitle = target.value;
    titleAutoSave.debouncedSave(target.value);
  }

  function handleDescriptionChange(e: Event) {
    const target = e.target as HTMLTextAreaElement;
    metaDescription = target.value;
    descriptionAutoSave.debouncedSave(target.value);
  }
</script>

<div class="space-y-6 pb-6">
  <Card>
    <CardHeader>
      <CardTitle>SEO Settings</CardTitle>
      <CardDescription>
        Optimize how this product appears in search engine results.
      </CardDescription>
    </CardHeader>
    <CardContent class="space-y-4">
      <div class="space-y-2">
        <Label for="metaTitle">Meta Title</Label>
        <Input
          id="metaTitle"
          value={metaTitle}
          oninput={handleTitleChange}
          onblur={() => titleAutoSave.immediateSave()}
          placeholder="Enter meta title"
        />
        <p class="text-xs text-muted-foreground">
          {metaTitle.length}/60 characters recommended
        </p>
      </div>

      <div class="space-y-2">
        <Label for="metaDescription">Meta Description</Label>
        <Textarea
          id="metaDescription"
          value={metaDescription}
          oninput={handleDescriptionChange}
          onblur={() => descriptionAutoSave.immediateSave()}
          placeholder="Enter meta description"
          rows={3}
        />
        <p class="text-xs text-muted-foreground">
          {metaDescription.length}/160 characters recommended
        </p>
      </div>

      <!-- Preview -->
      <div class="mt-6 p-4 rounded-lg border border-border bg-muted/30">
        <p class="text-xs text-muted-foreground mb-2">Search Result Preview</p>
        <div class="space-y-1">
          <p class="text-blue-600 dark:text-blue-400 text-lg font-medium truncate">
            {metaTitle || product.name || 'Product Title'}
          </p>
          <p class="text-green-700 dark:text-green-500 text-sm">
            yourstore.com/products/{product.slug}
          </p>
          <p class="text-sm text-muted-foreground line-clamp-2">
            {metaDescription || product.description || 'Product description will appear here...'}
          </p>
        </div>
      </div>
    </CardContent>
  </Card>
</div>

// packages/core/src/admin/components/product-seo-tab.tsx
import * as React from "react";
import type { Product } from "@/admin/hooks/use-products";
import { Label } from "@/admin/components/ui/label";
import { Input } from "@/admin/components/ui/input";
import { Textarea } from "@/admin/components/ui/textarea";
import { useUpdateProductMetadata } from "@/admin/hooks/use-products";
import { authClient } from "@/admin/lib/auth-client";
import { toast } from "sonner";
import { useSaveStatus } from "@/admin/contexts/save-status-context";
import { useAutoSave } from "@/admin/hooks/use-auto-save";

interface ProductSeoTabProps {
  product: Product;
}

export function ProductSeoTab({ product }: ProductSeoTabProps) {
  const { data: session } = authClient.useSession();
  const updateMetadata = useUpdateProductMetadata();
  const saveStatus = useSaveStatus();

  const [metaTitle, setMetaTitle] = React.useState(product.metaTitle);
  const [metaDescription, setMetaDescription] = React.useState(product.metaDescription);

  // Auto-save hooks for each field (debounced)
  const metaTitleAutoSave = useAutoSave(metaTitle, (val) => handleAutoSave("metaTitle", val));
  const metaDescriptionAutoSave = useAutoSave(metaDescription, (val) => handleAutoSave("metaDescription", val));

  // Reset local state when product changes
  React.useEffect(() => {
    setMetaTitle(product.metaTitle);
    setMetaDescription(product.metaDescription);
  }, [product.metaTitle, product.metaDescription, product.version]);

  const handleAutoSave = async (field: "metaTitle" | "metaDescription", value: string) => {
    if (!session?.user?.id) {
      toast.error("You must be logged in to update SEO metadata");
      return;
    }

    // Check if value actually changed
    const currentValue = field === "metaTitle" ? product.metaTitle : product.metaDescription;
    if (value === currentValue) return;

    saveStatus.startSaving();
    try {
      await updateMetadata.mutateAsync({
        id: product.aggregateId,
        userId: session.user.id,
        metaTitle: field === "metaTitle" ? value : metaTitle,
        metaDescription: field === "metaDescription" ? value : metaDescription,
        expectedVersion: product.version,
        fulfillmentType: product.productType,
      });
      saveStatus.completeSave();
    } catch (error) {
      // Revert to previous value on error
      if (field === "metaTitle") setMetaTitle(product.metaTitle);
      if (field === "metaDescription") setMetaDescription(product.metaDescription);

      saveStatus.failSave();
      toast.error(
        error instanceof Error ? error.message : "Failed to update SEO metadata"
      );
    }
  };

  const handleMetaTitleChange = (value: string) => {
    setMetaTitle(value);
    metaTitleAutoSave.debouncedSave(value);
  };

  const handleMetaTitleBlur = () => {
    metaTitleAutoSave.immediateSave();
  };

  const handleMetaTitleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      e.preventDefault();
      e.currentTarget.blur();
    }
  };

  const handleMetaDescriptionChange = (value: string) => {
    setMetaDescription(value);
    metaDescriptionAutoSave.debouncedSave(value);
  };

  const handleMetaDescriptionBlur = () => {
    metaDescriptionAutoSave.immediateSave();
  };

  const handleMetaDescriptionKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      e.currentTarget.blur();
    }
  };

  return (
    <div className="space-y-6 pb-6">
      {/* SEO Fields */}
      <div className="space-y-4 rounded-lg border border-border/60 p-4">
        <h3 className="text-sm font-semibold">Search Engine Optimization</h3>

        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="metaTitle">Meta Title</Label>
            <Input
              id="metaTitle"
              value={metaTitle}
              onChange={(e) => handleMetaTitleChange(e.target.value)}
              onBlur={handleMetaTitleBlur}
              onKeyDown={handleMetaTitleKeyDown}
              placeholder="Enter meta title..."
            />
            <p className="text-xs text-muted-foreground">
              Recommended length: 50-60 characters
            </p>
          </div>

          <div className="space-y-2">
            <Label htmlFor="metaDescription">Meta Description</Label>
            <Textarea
              id="metaDescription"
              value={metaDescription}
              onChange={(e) => handleMetaDescriptionChange(e.target.value)}
              onBlur={handleMetaDescriptionBlur}
              onKeyDown={handleMetaDescriptionKeyDown}
              placeholder="Enter meta description..."
              rows={4}
            />
            <p className="text-xs text-muted-foreground">
              Recommended length: 150-160 characters
            </p>
          </div>
        </div>
      </div>

      {/* Preview Section */}
      <div className="space-y-4 rounded-lg border border-border/60 p-4">
        <h3 className="text-sm font-semibold">Search Engine Preview</h3>

        <div className="space-y-2">
          <div>
            <div className="text-blue-600 text-sm font-medium line-clamp-1">
              {metaTitle || product.name}
            </div>
            <div className="text-green-700 dark:text-green-400 text-xs line-clamp-1">
              https://yourstore.com/products/{product.slug}
            </div>
            <div className="text-gray-600 dark:text-gray-400 text-sm line-clamp-2 mt-1">
              {metaDescription || product.description || "No description provided"}
            </div>
          </div>
        </div>
      </div>

      {/* URL & Slug Info */}
      <div className="space-y-4 rounded-lg border border-border/60 p-4">
        <h3 className="text-sm font-semibold">URL Information</h3>

        <div className="space-y-2">
          <div>
            <Label className="text-xs text-muted-foreground">Product URL</Label>
            <p className="text-sm font-mono bg-muted px-3 py-2 rounded-md mt-1">
              /products/{product.slug}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
