// packages/admin-ui/src/routes/signup/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { base } from '$app/paths';
  import { auth } from '$lib/stores/auth';
  import { Button, Input, Label, Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '$lib/components/ui';

  let name = $state('');
  let email = $state('');
  let password = $state('');
  let loading = $state(false);

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    loading = true;

    const success = await auth.signUp(email, password, name);

    if (success) {
      goto(`${base}/`);
    }

    loading = false;
  }
</script>

<div class="flex min-h-screen items-center justify-center bg-background p-4">
  <Card class="w-full max-w-md">
    <CardHeader class="text-center">
      <div class="mx-auto mb-4">
        <img src="{base}/logo.svg" alt="SlapCommerce" class="h-12 w-auto" />
      </div>
      <CardTitle class="text-2xl">Create an account</CardTitle>
      <CardDescription>Enter your details to get started</CardDescription>
    </CardHeader>
    <form onsubmit={handleSubmit}>
      <CardContent class="space-y-4">
        {#if $auth.error}
          <div class="rounded-md bg-destructive/10 p-3 text-sm text-destructive">
            {$auth.error}
          </div>
        {/if}

        <div class="space-y-2">
          <Label for="name">Name</Label>
          <Input
            id="name"
            type="text"
            placeholder="Your name"
            bind:value={name}
            required
            disabled={loading}
          />
        </div>

        <div class="space-y-2">
          <Label for="email">Email</Label>
          <Input
            id="email"
            type="email"
            placeholder="you@example.com"
            bind:value={email}
            required
            disabled={loading}
          />
        </div>

        <div class="space-y-2">
          <Label for="password">Password</Label>
          <Input
            id="password"
            type="password"
            placeholder="Create a password"
            bind:value={password}
            required
            disabled={loading}
          />
        </div>
      </CardContent>
      <CardFooter class="flex-col gap-4">
        <Button type="submit" class="w-full" disabled={loading}>
          {#if loading}
            Creating account...
          {:else}
            Sign up
          {/if}
        </Button>
        <p class="text-sm text-muted-foreground">
          Already have an account?
          <a href="{base}/login" class="text-primary hover:underline">Sign in</a>
        </p>
      </CardFooter>
    </form>
  </Card>
</div>

// src/routes/signup.tsx
import { createRoute, useNavigate, Link } from "@tanstack/react-router";
import { rootRoute } from "./__root";
import { useState } from "react";
import { authClient } from "@/lib/auth-client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export const signupRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: "/admin/signup",
  component: SignupPage,
});

function SignupPage() {
  const navigate = useNavigate();
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setIsLoading(true);

    try {
      const result = await authClient.signUp.email({
        email,
        password,
        name,
      });

      if (result.error) {
        setError(result.error.message || "Failed to sign up");
      } else {
        // Redirect to admin home page on success (auto sign-in happens)
        navigate({ to: "/admin" });
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "An unexpected error occurred");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen items-center justify-center p-8">
      <div className="w-full max-w-md space-y-8 rounded-lg border p-8">
        <div className="text-center">
          <h1 className="text-3xl font-bold">Create Admin Account</h1>
          <p className="mt-2 text-gray-600">Sign up to access the admin panel</p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="name">Name</Label>
            <Input
              id="name"
              type="text"
              placeholder="Your name"
              value={name}
              onChange={(e) => setName(e.target.value)}
              required
              disabled={isLoading}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              type="email"
              placeholder="admin@example.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              required
              disabled={isLoading}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              type="password"
              placeholder="Enter your password (min 8 characters)"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              minLength={8}
              disabled={isLoading}
            />
          </div>

          {error && (
            <div className="rounded-md bg-red-50 p-3 text-sm text-red-800 dark:bg-red-900/20 dark:text-red-400">
              {error}
            </div>
          )}

          <Button type="submit" className="w-full" disabled={isLoading}>
            {isLoading ? "Creating account..." : "Sign Up"}
          </Button>

          <div className="text-center text-sm">
            <span className="text-gray-600">Already have an account? </span>
            <Link to="/admin/login" className="text-blue-600 hover:underline">
              Sign in
            </Link>
          </div>
        </form>
      </div>
    </div>
  );
}
