// packages/admin-ui/src/lib/components/layout/SiteHeader.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { base } from '$app/paths';
  import { cn } from '$lib/utils/cn';
  import { theme, resolvedTheme } from '$lib/stores/theme';
  import { Button } from '$lib/components/ui';

  interface Props {
    onToggleSidebar?: () => void;
    class?: string;
  }

  let { onToggleSidebar, class: className }: Props = $props();

  function getPageTitle(pathname: string): string {
    // Remove base path and leading/trailing slashes
    const withoutBase = pathname.replace(base, '');
    const segments = withoutBase.replace(/^\/|\/$/g, '').split('/');
    const pageName = segments[segments.length - 1] || 'Dashboard';

    if (pageName === '' || pageName === 'admin') {
      return 'Dashboard';
    }

    // Convert kebab-case to Title Case
    return pageName
      .split(/[-_]/)
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }

  let pageTitle = $derived(getPageTitle($page.url.pathname));
</script>

{#snippet panelLeftIcon()}
  <svg class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    <rect width="18" height="18" x="3" y="3" rx="2"/>
    <path d="M9 3v18"/>
  </svg>
{/snippet}

{#snippet sunIcon()}
  <svg class="size-4 transition-transform group-hover:rotate-180 group-hover:text-amber-500" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    <circle cx="12" cy="12" r="4"/>
    <path d="M12 2v2"/>
    <path d="M12 20v2"/>
    <path d="m4.93 4.93 1.41 1.41"/>
    <path d="m17.66 17.66 1.41 1.41"/>
    <path d="M2 12h2"/>
    <path d="M20 12h2"/>
    <path d="m6.34 17.66-1.41 1.41"/>
    <path d="m19.07 4.93-1.41 1.41"/>
  </svg>
{/snippet}

{#snippet moonIcon()}
  <svg class="size-4 transition-transform group-hover:-rotate-12 group-hover:text-indigo-400" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
    <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"/>
  </svg>
{/snippet}

<header class={cn(
  'hidden md:flex h-14 shrink-0 items-center gap-2 border-b border-border bg-background/80 backdrop-blur-sm',
  className
)}>
  <div class="flex w-full items-center gap-1 px-4 lg:gap-2 lg:px-6">
    <!-- Sidebar toggle -->
    <Button
      variant="ghost"
      size="sm"
      onclick={onToggleSidebar}
      class="-ml-1 transition-transform hover:scale-110 hover:text-primary"
    >
      {@render panelLeftIcon()}
    </Button>

    <!-- Separator -->
    <div class="mx-2 h-4 w-px bg-gradient-to-b from-transparent via-border to-transparent"></div>

    <!-- Page title -->
    <h1
      class="text-xl font-bold tracking-tight"
      style="font-family: var(--font-display);"
    >
      {pageTitle}
    </h1>

    <!-- Right side -->
    <div class="ml-auto flex items-center gap-2">
      <!-- Theme toggle -->
      <Button
        variant="ghost"
        size="sm"
        onclick={() => theme.toggleTheme()}
        class="group relative overflow-visible"
        aria-label="Toggle theme"
      >
        {#if $resolvedTheme === 'dark'}
          {@render sunIcon()}
        {:else}
          {@render moonIcon()}
        {/if}
        <span class="absolute -bottom-8 left-1/2 -translate-x-1/2 text-xs opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap pointer-events-none">
          {$resolvedTheme === 'dark' ? 'Light' : 'Dark'} mode
        </span>
      </Button>
    </div>
  </div>
</header>

// src/components/site-header.tsx
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { SidebarTrigger } from "@/components/ui/sidebar";
import { useLocation } from "@tanstack/react-router";
import { useTheme } from "next-themes";
import { Moon, Sun } from "lucide-react";
import { useEffect, useState } from "react";

function getPageTitle(pathname: string): string {
  // Remove leading/trailing slashes and split
  const segments = pathname.replace(/^\/|\/$/g, "").split("/");

  // Get the last segment (the actual page)
  const page = segments[segments.length - 1] || "Dashboard";

  // Capitalize first letter and handle special cases
  if (page === "admin" || page === "") {
    return "Dashboard";
  }

  // Convert kebab-case or camelCase to Title Case
  return page
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

export function SiteHeader() {
  const location = useLocation();
  const { theme, setTheme, resolvedTheme } = useTheme();
  const [mounted, setMounted] = useState(false);

  // Avoid hydration mismatch
  useEffect(() => {
    setMounted(true);
  }, []);

  const pageTitle = getPageTitle(location.pathname);

  const toggleTheme = () => {
    if (theme === "system") {
      // If system, toggle to the opposite of current resolved theme
      setTheme(resolvedTheme === "dark" ? "light" : "dark");
    } else {
      // Toggle between light and dark
      setTheme(theme === "dark" ? "light" : "dark");
    }
  };

  // Use resolvedTheme for icon display (accounts for system theme)
  const isDark = resolvedTheme === "dark";

  return (
    <header className="flex h-(--header-height) shrink-0 items-center gap-2 border-b transition-smooth ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-(--header-height) relative backdrop-blur-sm bg-background/80">
      <div className="flex w-full items-center gap-1 px-4 lg:gap-2 lg:px-6">
        <SidebarTrigger className="-ml-1 transition-smooth hover:scale-110 hover:text-primary" />
        <Separator
          orientation="vertical"
          className="mx-2 data-[orientation=vertical]:h-4 bg-gradient-to-b from-transparent via-border to-transparent"
        />
        <h1
          className="text-base font-bold tracking-tight bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text transition-smooth hover:from-primary hover:to-fantasy-purple"
          style={{ fontFamily: "var(--font-display)" }}
        >
          {pageTitle}
        </h1>
        <div className="ml-auto flex items-center gap-2">
          {mounted && (
            <Button
              variant="ghost"
              size="sm"
              className="hidden sm:flex group relative overflow-visible"
              onClick={toggleTheme}
              aria-label="Toggle theme"
            >
              {isDark ? (
                <Sun className="h-4 w-4 transition-smooth group-hover:rotate-180 group-hover:text-ornament-gold" />
              ) : (
                <Moon className="h-4 w-4 transition-smooth group-hover:-rotate-12 group-hover:text-fantasy-purple" />
              )}
              <span className="absolute -bottom-8 left-1/2 -translate-x-1/2 text-xs opacity-0 group-hover:opacity-100 transition-smooth whitespace-nowrap pointer-events-none">
                {isDark ? "Light" : "Dark"} mode
              </span>
            </Button>
          )}
        </div>
      </div>
    </header>
  );
}
