// packages/admin-ui/src/lib/components/ui/Label.svelte
<script lang="ts">
  import { cn } from '$lib/utils/cn';

  interface Props {
    for?: string;
    class?: string;
    children?: import('svelte').Snippet;
  }

  let {
    for: htmlFor,
    class: className,
    children
  }: Props = $props();

  const baseStyles = 'text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70';
</script>

<label
  for={htmlFor}
  class={cn(baseStyles, className)}
>
  {#if children}
    {@render children()}
  {/if}
</label>

// packages/core/src/admin/components/ui/label.tsx
"use client"

import * as React from "react"
import * as LabelPrimitive from "@radix-ui/react-label"

import { cn } from "@/admin/lib/utils"

function Label({
  className,
  ...props
}: React.ComponentProps<typeof LabelPrimitive.Root>) {
  return (
    <LabelPrimitive.Root
      data-slot="label"
      className={cn(
        "flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50",
        className
      )}
      {...props}
    />
  )
}

export { Label }
