// packages/core/src/admin/components/product-fulfillment-tab.tsx
import * as React from "react";
import type { Product } from "@/admin/hooks/use-products";
import { Label } from "@/admin/components/ui/label";
import { Input } from "@/admin/components/ui/input";
import {
  useUpdateProductClassification,
  useUpdateDropshipProductSafetyBuffer,
} from "@/admin/hooks/use-products";
import { authClient } from "@/admin/lib/auth-client";
import { toast } from "sonner";
import { useSaveStatus } from "@/admin/contexts/save-status-context";
import { useAutoSave } from "@/admin/hooks/use-auto-save";

interface ProductFulfillmentTabProps {
  product: Product;
}

export function ProductFulfillmentTab({ product }: ProductFulfillmentTabProps) {
  const { data: session } = authClient.useSession();
  const updateClassification = useUpdateProductClassification();
  const updateSafetyBuffer = useUpdateDropshipProductSafetyBuffer();
  const saveStatus = useSaveStatus();

  const [vendor, setVendor] = React.useState(product.vendor);
  const [dropshipSafetyBuffer, setDropshipSafetyBuffer] = React.useState(
    product.dropshipSafetyBuffer || 0
  );

  // Auto-save hooks
  const vendorAutoSave = useAutoSave(vendor, (val) => handleAutoSaveVendor(val));
  const bufferAutoSave = useAutoSave(dropshipSafetyBuffer, (val) =>
    handleAutoSaveBuffer(val)
  );

  // Reset local state when product changes
  React.useEffect(() => {
    setVendor(product.vendor);
    setDropshipSafetyBuffer(product.dropshipSafetyBuffer || 0);
  }, [product.vendor, product.dropshipSafetyBuffer, product.version]);

  const handleAutoSaveVendor = async (value: string) => {
    if (!session?.user?.id) {
      toast.error("You must be logged in to update products");
      return;
    }

    if (value === product.vendor) return;

    saveStatus.startSaving();
    try {
      await updateClassification.mutateAsync({
        id: product.aggregateId,
        userId: session.user.id,
        vendor: value,
        expectedVersion: product.version,
        fulfillmentType: product.productType,
      });
      saveStatus.completeSave();
    } catch (error) {
      setVendor(product.vendor);
      saveStatus.failSave();
      toast.error(
        error instanceof Error ? error.message : "Failed to update vendor"
      );
    }
  };

  const handleAutoSaveBuffer = async (value: number) => {
    if (!session?.user?.id) {
      toast.error("You must be logged in to update products");
      return;
    }

    if (value === product.dropshipSafetyBuffer) return;

    saveStatus.startSaving();
    try {
      await updateSafetyBuffer.mutateAsync({
        id: product.aggregateId,
        userId: session.user.id,
        safetyBuffer: value,
        expectedVersion: product.version,
      });
      saveStatus.completeSave();
    } catch (error) {
      setDropshipSafetyBuffer(product.dropshipSafetyBuffer || 0);
      saveStatus.failSave();
      toast.error(
        error instanceof Error ? error.message : "Failed to update safety buffer"
      );
    }
  };

  const handleVendorChange = (value: string) => {
    setVendor(value);
    vendorAutoSave.debouncedSave(value);
  };

  const handleBufferChange = (value: string) => {
    const numVal = parseInt(value) || 0;
    setDropshipSafetyBuffer(numVal);
    bufferAutoSave.debouncedSave(numVal);
  };

  const handleVendorBlur = () => vendorAutoSave.immediateSave();
  const handleBufferBlur = () => bufferAutoSave.immediateSave();

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      e.preventDefault();
      e.currentTarget.blur();
    }
  };

  return (
    <div className="space-y-6 pb-6">
      {/* Vendor Section */}
      <div className="space-y-4 rounded-lg border border-border/60 p-4">
        <h3 className="text-sm font-semibold">Supplier Information</h3>

        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="vendor">Vendor</Label>
            <Input
              id="vendor"
              value={vendor}
              onChange={(e) => handleVendorChange(e.target.value)}
              onBlur={handleVendorBlur}
              onKeyDown={handleKeyDown}
              placeholder="Enter vendor name..."
            />
            <p className="text-xs text-muted-foreground">
              The supplier or manufacturer of this product
            </p>
          </div>
        </div>
      </div>

      {/* Inventory Settings */}
      <div className="space-y-4 rounded-lg border border-border/60 p-4">
        <h3 className="text-sm font-semibold">Inventory Settings</h3>

        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="safetyBuffer">Dropship Safety Buffer</Label>
            <Input
              id="safetyBuffer"
              type="number"
              min="0"
              value={dropshipSafetyBuffer}
              onChange={(e) => handleBufferChange(e.target.value)}
              onBlur={handleBufferBlur}
              onKeyDown={handleKeyDown}
            />
            <p className="text-xs text-muted-foreground">
              Reserve this many units to prevent overselling. The available
              inventory shown to customers will be reduced by this amount.
            </p>
          </div>
        </div>
      </div>

      {/* Info Section */}
      <div className="space-y-4 rounded-lg border border-border/60 p-4 bg-muted/30">
        <h3 className="text-sm font-semibold">About Dropship Fulfillment</h3>
        <div className="text-sm text-muted-foreground space-y-2">
          <p>
            Dropship products are fulfilled directly by your supplier. When a
            customer places an order, the order is forwarded to your supplier
            who ships directly to the customer.
          </p>
          <p>
            <strong>Safety Buffer:</strong> Use this to account for inventory
            sync delays between your store and supplier. A buffer of 5 means
            if your supplier has 100 units, customers will only see 95
            available.
          </p>
        </div>
      </div>
    </div>
  );
}

// packages/admin-ui/src/lib/components/products/ProductFulfillmentTab.svelte
<script lang="ts">
  import { Label, Input, Card, CardHeader, CardTitle, CardDescription, CardContent } from '$lib/components/ui';
  import { productsStore, type Product } from '$lib/stores/products';
  import { currentUser } from '$lib/stores/auth';
  import { saveStatusStore } from '$lib/stores/save-status';
  import { toast } from '$lib/stores/toast';
  import { createAutoSave } from '$lib/utils/auto-save';

  interface Props {
    product: Product;
  }

  let { product }: Props = $props();

  let safetyBuffer = $state('');

  // Sync when product changes
  $effect(() => {
    safetyBuffer = product.dropshipSafetyBuffer?.toString() || '';
  });

  const safetyBufferAutoSave = createAutoSave(async (value: string) => {
    if (!$currentUser?.id) {
      toast.error('You must be logged in to update products');
      return;
    }

    const numValue = parseInt(value, 10);
    if (isNaN(numValue) || numValue === product.dropshipSafetyBuffer) return;

    saveStatusStore.startSaving();
    try {
      await productsStore.updateDropshipProductSafetyBuffer({
        id: product.aggregateId,
        userId: $currentUser.id,
        safetyBuffer: numValue,
        expectedVersion: product.version
      });
      saveStatusStore.completeSave();
      await productsStore.fetchProducts();
    } catch (error) {
      saveStatusStore.failSave();
      toast.error(error instanceof Error ? error.message : 'Failed to update safety buffer');
    }
  });

  function handleSafetyBufferChange(e: Event) {
    const target = e.target as HTMLInputElement;
    safetyBuffer = target.value;
    safetyBufferAutoSave.debouncedSave(target.value);
  }

  function handleSafetyBufferBlur() {
    safetyBufferAutoSave.immediateSave();
  }
</script>

<div class="space-y-6 pb-6">
  <Card>
    <CardHeader>
      <CardTitle>Dropship Fulfillment</CardTitle>
      <CardDescription>
        Configure fulfillment settings for this dropship product.
      </CardDescription>
    </CardHeader>
    <CardContent class="space-y-4">
      <div class="space-y-2">
        <Label for="safetyBuffer">Safety Buffer (days)</Label>
        <Input
          id="safetyBuffer"
          type="number"
          value={safetyBuffer}
          oninput={handleSafetyBufferChange}
          onblur={handleSafetyBufferBlur}
          placeholder="Enter safety buffer in days"
        />
        <p class="text-xs text-muted-foreground">
          Additional days added to estimated delivery time as a buffer.
        </p>
      </div>

      {#if product.fulfillmentProviderId}
        <div class="space-y-2">
          <Label>Fulfillment Provider</Label>
          <p class="text-sm text-muted-foreground">{product.fulfillmentProviderId}</p>
        </div>
      {/if}

      {#if product.supplierSku}
        <div class="space-y-2">
          <Label>Supplier SKU</Label>
          <p class="text-sm text-muted-foreground">{product.supplierSku}</p>
        </div>
      {/if}

      {#if product.supplierCost !== null}
        <div class="space-y-2">
          <Label>Supplier Cost</Label>
          <p class="text-sm text-muted-foreground">${product.supplierCost.toFixed(2)}</p>
        </div>
      {/if}
    </CardContent>
  </Card>
</div>
